- hosts: client
  become: true
  roles:
    - client

- name: set up server
  hosts: server
  become: yes
  roles:
    - name: server
      vars:
        flag: "{{ user_flag }} - Wie funktioniert ssh ohne Passworteingabe?"
        flag_2: "{{ root_flag }}"

- hosts: home
  become: true
  roles:
    - kali
